name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
    
  cached_network_image:
  uuid: ^3.0.7
  intl: ^0.18.1
  flutter_fortune_wheel: ^1.2.1
  persistent_bottom_nav_bar: ^5.0.2
  flutter_svg: ^2.0.7
  confetti: ^0.7.0
  qrscan: ^0.3.3
  scratcher: ^2.3.0
  ticket_widget: ^0.0.1
  show_up_animation: ^2.0.0
  flutter_staggered_grid_view: ^0.6.2
  scroll_loop_auto_scroll: ^0.0.5
  scrollable_positioned_list: ^0.3.8
  barcode: ^2.2.4
  syncfusion_flutter_barcodes: ^22.1.37
  get: ^4.6.5
  animated_rotating_widget: ^0.0.2
  flutter_splash_screen: ^1.0.0+6
  full_screen_image: ^2.0.0
  flutter_slidable: ^3.0.0



dev_dependencies:
    flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/karaca logo.jpg"
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true  
  assets:
        - images/karaca-yeni4371.jpg
        



